# Generated by Django 4.0.4 on 2022-05-23 06:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('u_nickname', models.TextField()),
                ('u_email', models.EmailField(max_length=254, unique=True)),
                ('u_access_token', models.TextField(null=True)),
                ('u_warn_count', models.IntegerField(default=0)),
                ('u_active', models.IntegerField(default=0)),
                ('penalty_date', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('u_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tester.user')),
                ('m_tel', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('r_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room', to='tester.room')),
                ('u_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writer', to='tester.user')),
            ],
        ),
    ]
